export const projects = [
    {
      id: 1,
      Owner: 'Computer Science Major',
      CreatedDate: '2023-10-01',
      Title: 'AI Chatbot for Student Assistance',
      Description: 'Developing an AI chatbot to assist students with common queries related to courses, schedules, and campus services.',
      Members: ['John Doe', 'Alice Smith'],
      Image_Link: 'https://picsum.photos/200',
      Tags: ['Freshman', 'AI'],
    },
    {
      id: 2,
      Owner: 'Electrical Engineering Major',
      CreatedDate: '2023-10-15',
      Title: 'Smart Home Automation System',
      Description: 'Creating a smart home automation system that integrates IoT devices to enhance energy efficiency and security.',
      Members: ['Bob Johnson', 'Eva Martinez'],
      Image_Link: 'https://picsum.photos/300',
      Tags: ['Sophomore', 'IoT'],
    },
    {
      id: 3,
      Owner: 'Business Administration Major',
      CreatedDate: '2023-10-15',
      Title: 'E-commerce Platform for Student Entrepreneurs',
      Description: 'Building an e-commerce platform to empower student entrepreneurs to showcase and sell their products online.',
      Members: ['Charlie Brown', 'Grace Wang'],
      Image_Link: 'https://picsum.photos/400',
      Tags: ['Junior', 'E-commerce'],
    },
    {
      id: 4,
      Owner: 'Mechanical Engineering Major',
      CreatedDate: '2023-10-15',
      Title: 'Solar-Powered Campus Shuttle',
      Description: 'Designing and implementing a solar-powered shuttle service to transport students within the campus.',
      Members: ['David Miller', 'Sophie Chen'],
      Image_Link: 'https://picsum.photos/500',
      Tags: ['Senior', 'Sustainability'],
    },
    {
      id: 5,
      Owner: 'Graphic Design Major',
      CreatedDate: '2023-10-15',
      Title: 'Campus Event Poster Design',
      Description: 'Collaborating on creating visually appealing posters for campus events and activities.',
      Members: ['Emma Davis', 'Michael Lee'],
      Image_Link: 'https://picsum.photos/600',
      Tags: ['Sophomore', 'Design'],
    },
    {
      id: 6,
      Owner: 'Environmental Science Major',
      CreatedDate: '2023-10-15',
      Title: 'Campus Sustainability Project',
      Description: 'Working on initiatives to promote sustainability on campus, including waste reduction and energy conservation.',
      Members: ['Olivia Taylor', 'Daniel Kim'],
      Image_Link: 'https://picsum.photos/700',
      Tags: ['Junior', 'Sustainability'],
    },
    {
      id: 7,
      Owner: 'Psychology Major',
      CreatedDate: '2023-10-20',
      Title: 'Mental Health Awareness Campaign',
      Description: 'Launching a campaign to raise awareness about mental health issues and promote well-being on campus.',
      Members: ['Sophia Adams', 'Jackson Smith'],
      Image_Link: 'https://picsum.photos/800',
      Tags: ['Senior', 'Mental Health'],
    },
    {
      id: 8,
      Owner: 'Biochemistry Major',
      CreatedDate: '2023-10-25',
      Title: 'Biomedical Research Project',
      Description: 'Conducting research in the field of biochemistry to explore innovative solutions for healthcare challenges.',
      Members: ['Isabella Garcia', 'Liam Johnson'],
      Image_Link: 'https://picsum.photos/1200',
      Tags: ['Senior', 'Research'],
    },
    {
      id: 9,
      Owner: 'Music Major',
      CreatedDate: '2023-10-28',
      Title: 'Collaborative Music Composition',
      Description: 'Collaborating on creating a musical composition involving students from various musical backgrounds.',
      Members: ['Aiden Thompson', 'Natalie Clark'],
      Image_Link: 'https://picsum.photos/1100',
      Tags: ['Sophomore', 'Music'],
    },
    {
      id: 10,
      Owner: 'Political Science Major',
      CreatedDate: '2023-11-01',
      Title: 'Student Government Elections',
      Description: 'Organizing and managing student government elections to encourage active student participation in governance.',
      Members: ['Lucas Brown', 'Ella Davis'],
      Image_Link: 'https://picsum.photos/1000',
      Tags: ['Junior', 'Governance'],
    },
    {
      id: 11,
      Owner: 'History Major',
      CreatedDate: '2023-11-05',
      Title: 'Historical Research Project',
      Description: 'Conducting research on a specific historical period to contribute new insights to the field of history.',
      Members: ['Sophie Turner', 'William Martinez'],
      Image_Link: 'https://picsum.photos/900',
      Tags: ['Senior', 'History'],
    },
    {
      id: 12,
      Owner: 'Chemical Engineering Major',
      CreatedDate: '2023-11-10',
      Title: 'Chemical Process Optimization',
      Description: 'Optimizing chemical processes to enhance efficiency and reduce environmental impact in industrial settings.',
      Members: ['Daniel Walker', 'Ava White'],
      Image_Link: 'https://picsum.photos/800',
      Tags: ['Junior', 'Chemical Engineering'],
    },
  ];